### ISSUE TITLE
Problem with UTF-8 encoding on Windows

### ISSUE THREAD

**Issue by malek-luky** [cvut/QtMips#11]
Loading the elf executable on windows containing path or file name with diacritic cause an error that no file has been found.

**Comment by ppisa** [comment]
I know the source of the problem.

The ELF executable path is translated from QString to C 8-bit string at the line

https://github.com/cvut/QtMips/blob/master/qtmips_machine/qtmipsmachine.cpp#L50

    ProgramLoader program(cc.elf());

It is easy to change ProgramLoader argument to QString. But it is a problem what to to with
the QString string later in

https://github.com/cvut/QtMips/blob/master/qtmips_machine/programloader.cpp#L56

    if ((this->fd = open(file, O_RDONLY | O_BINARY, 0)) < 0)

It is necessary to pass plain C file descriptor to ELF library. 

It seems that t would be possible to open file as QFile which would interpret QString correctly and then pass obtained handle to the ELF library

https://doc.qt.io/qt-5/qfiledevice.html#handle

    int QFileDevice::handle() const

I can prepare development branch if somebody can compile and test the code on real Windows (I use only wine) with some local language support. I can even cross-compile, prepare Windows test build if there is interest.

**Comment by ppisa** [comment]
Lukáš Málek confirms that fix works by test on real Windows as well.
