### ISSUE TITLE
AppImage does not run on Ubuntu Xenial

### ISSUE THREAD

**Issue by probonopd** [cvut/QtMips#5]
```
Cannot load library /run/firejail/appimage/.appimage-9192/bin/platforms/libqxcb.so: (libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory)

QLibraryPrivate::loadPlugin failed on "/run/firejail/appimage/.appimage-9192/bin/platforms/libqxcb.so" : "Cannot load library /run/firejail/appimage/.appimage-9192/bin/platforms/libqxcb.so: (libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory)"

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
```

Full debug output:
https://travis-ci.org/github/AppImage/appimage.github.io/builds/675837479

Reference:
https://github.com/AppImage/appimage.github.io/pull/1961

**Comment by ppisa** [comment]
Hello Probonopd

the first thanks for testing QtMips in APPimage format. I do not have experience with APPimage. Basic build is thanks to Frantisek Vacek contribution. I would expect that inclusion of libxkbcommon-x11.so.0 in the image is not the right solution because it should match the one distributed with X11. But may it be it is right to put more libraries into package .... I am not sure.

As for Ubuntu Xenial, we have packages specially built for that version and they should be OK. But I personally use no Ubuntu, so packages are build without real testing. But next comamnds sequence is tested by many students of our course https://cw.fel.cvut.cz/wiki/courses/b35apo/en/start
```
sudo add-apt-repository ppa:ppisa/qtmips
sudo apt-get update
sudo apt-get install qtmips
```
But I would like to have as good APPimage as possible. Suggestions or pointers to examples  (i.e. other basic Qt5 using applications) are welcome.

Best wishes,

Pavel Pisa

**Comment by probonopd** [comment]
Hello @ppisa thanks for your response. How was https://github.com/cvut/QtMips/releases/download/v0.7.3/qtmips-0.7.3-x86_64.AppImage produced? Can you please add `libxkbcommon-x11.so.0` to it, then I can re-run the test and let you know the results. 

Thank you very much.

**Comment by ppisa** [comment]
The AppImage has been prepared by my colleague on his own computer. I do not know exact setup.

I have prepared 0.7.5 release of QtMips and managed Suse Open Build Service to prepare AppImage this time. It pushes back to ancient Qt5.6 version and other troubles but I expect that portability should be much better now.

Please, if you can, test the result and give us feedback.

**Comment by probonopd** [comment]
@ppisa do you have a download link for me please? Thanks a lot.

**Comment by ppisa** [comment]
The build is from Suse Open Build Service, available there

https://download.opensuse.org/repositories/home:/ppisa/AppImage/QtMips-latest-x86_64.AppImage

It is copied into QtMips 0.7.5 release on GitHub as well.

**Comment by ppisa** [comment]
@probonopd please, did the provided link solve the problem?  This build is against libraries chosen by SUSE fr AppImages which should be portable to the most GNU/Linux environments.

Tanks for testing,

Pavel

**Comment by probonopd** [comment]
Running a test. Let's see how it goes.

**Comment by ppisa** [comment]
Please @probonopd , can you report actual state of your appimage builds/use for QtMips repo master and devel branches. If it works then please close this issue.

**Comment by ppisa** [comment]
No response for almost year

**Comment by probonopd** [comment]
Thanks @ppisa, the test went well, as indicated by the green arrow [on 13 Feb 2021](https://github.com/cvut/QtMips/issues/5#ref-commit-657c33c).

QtMips is in the catalog ever since:
https://appimage.github.io/QtMips/

Thank you very much! :+1:

**Comment by ppisa** [comment]
Thanks for the report.

It seems that the last build is relatively old Tue, 21 Dec 2021 05:55:22 based on 0.7.x version.

We have switched to CMake for future 0.8.x versions and there seems to be problem with automatic AppImage builds on Suse Open Build Service

https://build.opensuse.org/package/live_build_log/home:ppisa/qtmips/AppImage/x86_64

So this is probably for new issue and problem is that we probably cannot build with older Qt5 which is used in OBS.  Know to work old Qt5 version - Qt5 5.9.5 which we use for Ubuntu 18.4.1 QtMips build. See

https://code.launchpad.net/~ppisa/+recipe/qtmips-build

Build with Qt5 5.6.2 used for discussed OBS AppImage build is not feasible anymore... I am not sure what are other options for AppImage build.

https://build.opensuse.org/package/show/home:ppisa/qtmips

Generally our main activity is ongoing on RISC-V simulator version now.

https://github.com/cvut/qtrvsim

But it requires alt least Qt5 5.9.x as bare minimum as well.

https://build.opensuse.org/package/show/home:jdupak/qtrvsim

https://code.launchpad.net/~qtrvsimteam/+recipe/qtrvsim-build

We have FlatPack build for it available. AppImage would be interesting but time is limited...

If you have some idea, document it as issue in QtRvSim GitHub project.

**Comment by probonopd** [comment]
For Ubuntu there are Qt builds of 5.15.x even for very old distribution releases.
Probably openSUSE/OBS could do the same, but I don't know whether it has been done. Maybe @adrianschroeter can help?
