### ISSUE TITLE
QtChooser deprecation on Arch Linux

### ISSUE THREAD

**Issue by petrzjunior** [cvut/QtMips#6]
`qtchooser` seems to be a deprecated tool, since `qmake` itself [can find Qt version](https://wiki.archlinux.org/index.php/Qt#Default_Qt_toolkit) with `QT_SELECT=5` environmental variable.

More precisely there is a severe conflict in AUR-based systems (such as Arch Linux, Gentoo and others). Packages [qtchooser](https://aur.archlinux.org/packages/qtchooser/) and [qt5-base](https://www.archlinux.org/packages/extra/x86_64/qt5-base/) cannot be installed together, because `qt5-base` is basically superset of `qtchooser` now.

Provided you have only one Qt version installed, problem can be solved by directly calling `qmake` in `build.sh`:
```diff
-qtchooser -run-tool=qmake -qt=5 -recursive "$ROOT" "QMAKE_RPATHDIR += ../qtmips_machine ../qtmips_osemu ../qtmips_asm"
+qmake -recursive "$ROOT" "QMAKE_RPATHDIR += ../qtmips_machine ../qtmips_osemu ../qtmips_asm"
```
In case there are more Qt versions installed, it might be worth adding the `QT_SELECT=5` into that script. I suggest checking on other distros if this the case as well and maybe go with one of these solutions.

P.S. It might be even worth pushing QtMips into Arch User Repository as a package. The procedure is not difficult at all and I can assist you.

**Comment by ppisa** [comment]
Thanks for report. I am not sure what is the best solution to document.

I usually call directly 

`/usr/lib/x86_64-linux-gnu/qt5/bin/qmake`

which is really reliable that no incorrect qmake version is chosen. But the location can differ between distributions....

**Comment by petrzjunior** [comment]
@ppisa For me, qmake is installed at `/usr/bin/qmake`, so I can call directly `$ qmake`. Is this different on other distros? Do you have to use an absolute path insto `/usr/lib/...`?

**Comment by ppisa** [comment]
May it be `/usr/bin/qmake` is symlink in your case. It is link to `/usr/bin/qtchooser` in my case on stable Debian. On older, it was Qt4 version and Qt5 was available as `/usr/bin/qmake-qt5` etc...

The absolute path to lib ensures that all these layers are skipped and correct version is run. But that is not ideal. I try to discuss what is the better solution with @fvacek who knows Qt much better than me.

**Comment by petrzjunior** [comment]
> May it be /usr/bin/qmake is symlink in your case.

In my case, it is installed directly in `/usr/bin/qmake` and there is a symlink from `/usr/bin/qmake-qt5`.

**Comment by fvacek** [comment]
Hi, my opinion is that:
* we should avoid scripts like `build.sh`. `qmake -r CONFIG+=... && make && make install` should be standard path.
* If some build script is necessary to be created, from any `good` reason, than here should be always option to choose Qt version and c++ version used by this script.

**Comment by ppisa** [comment]
The reference to QtChooser and its use has been removed in the commit  95433b7858d9d22adbc134094733af5a823643d4 Project: c++14, sanitizer, tests, buildscript, designator syntax.
