### ISSUE TITLE
Memory model redesign (discusion & progress)

### ISSUE THREAD

**Issue by jdupak** [cvut/QtMips#9]
Result of meeting with @HollMax on 18.7.2020:

Class `MemoryAccess` interface will be split to `FrontendMemory` and `BackendMemory`.

Frontend memory subclasses are accessible by upper layers (e.g. GUI/CLI), contain access statistics and, most importantly, frontend memory is always addressed by full guest virtual memory. To differentiate guest virtual memory a new type will be introduced (`machine:: Address`). Frontend memory also always assumes guest endianness. The interface between frontend and backend is naturally provided by the MMU (transformation of class `PhysAddrSpace`).

MMU itself implements frontend interface so it can be used as raw memory access by upper layers or prepended by another frontend - most commonly cache (possibly multiple levels). MMUs cannot be chained as MMU signature is `frontend->backend` or when looking at addressing: frontend `Address` |--> backend internally defined `Offset`.

Backend memory represents real memory (current allocation will not be changed in this phase), periphery, or mmaped region (not implemented yet). Backend memory is accessed by an internally defined relative offset. As offset type is never exposed we have chosen typedef of `uint64_t` as type (`Offset`). We have not decided whether backend memory should collect statistics. We will continue on the assumption that it is not necessary until the opposite is proven. Moving statistics from the backend to region description struct (`RangeDesc`) in the MMU is considered a viable option.

Fetching and storing of other sizes will be reimplemented as a single method taking enum determining size and union supporting all required sizes (byte-dword). Any part of memory might be allowed to perform native size fetch instead of smaller fetch and split larger fetches to native-size aligned fetched when it makes sense for the HW emulated.

**Project structure changes**:

To emphasize that memory is a self-contained module accessed via interfaces, we have decided to create a new directory in `qtmips_machine` where all memory model files will be moved to. Also, the backend memory interface and subclasses will get its own subdirectory in memory directory. A separate namespace inside `machine` is under consideration. The frontend will not be separated for now as it contains low amount of files (only cache and interface). MMU shall not be included in frontend as it depends on both frontend and backend.

The above changes together with basic refactoring will be performed by @jdupak in a separate branch in the working fork ([/HollMax/QtMips](https://github.com/HollMax/QtMips/)) and review by @HollMax.

**Comment by ppisa** [comment]
The memory model rewrite has been finished by @jdupak and is documented in his bachelor thesis [Graphical RISC-V Architecture
Simulator - Memory Model and Project Management](https://dspace.cvut.cz/bitstream/handle/10467/94446/F3-BP-2021-Dupak-Jakub-thesis.pdf). The result allowing big and little endian support is included in the branch https://github.com/cvut/QtMips/tree/devel of the QtMips projects and well as in the RISC-V version of the simulator.
